before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: procgo
    dir: client
    binary: procgo
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
  - id: procgo-daemon
    dir: daemon
    binary: procgo-daemon
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
archives:
  - replacements:
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: '{{ .Tag }}-next'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
